max_width = 100
tab_spaces = 4
indentation_style = "Auto"
newline_style = "Unix"
attr_value_brace_style = "WhenRequired"
macro_names = [ "leptos::view", "view" ]
closing_tag_style = "Preserve"

[attr_values]
class = "Tailwind"
