[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true
inject_scripts = true
minify = "on_release"

[watch]
watch = []
ignore = []


[serve]
addresses = ["127.0.0.1"]
port = 6769
open = false
